language: r
cache: packages
latex: false
pandoc: false
fortran: false

r_check_args: '--no-manual'

matrix:
  include:
    - os: linux
    - os: osx
    - os: osx
      r: 3.6
      osx_image: xcode7.3
      disable_homebrew: true
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf
